services:
  - type: web
    name: power-monitor
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://hovomkrt_db_user:MHA1989Hovosavior19dan@cluster0.0g0rrzs.mongodb.net/?appName=Cluster0